In [551]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tmdb-movie-metadata/tmdb_5000_credits.csv
/kaggle/input/tmdb-movie-metadata/tmdb_5000_movies.csv
/kaggle/input/imdb-5000-movie-dataset/movie_metadata.csv
/kaggle/input/the-movies-dataset/links_small.csv
/kaggle/input/the-movies-dataset/ratings.csv
/kaggle/input/the-movies-dataset/links.csv
/kaggle/input/the-movies-dataset/keywords.csv
/kaggle/input/the-movies-dataset/movies_metadata.csv
/kaggle/input/the-movies-dataset/credits.csv
/kaggle/input/the-movies-dataset/ratings_small.csv

In [552]:
import matplotlib.pyplot as plt
pd.set_option('display.max_columns',100)
pd.set_option('display.max_colwidth',80)

In [553]:
old_data=pd.read_csv('../input/imdb-5000-movie-dataset/movie_metadata.csv')

In [554]:
old_data.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pirate|singapore,http://www.imdb.com/title/tt0449088/?ref_=fn_tt_tt_1,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_tt_tt_1,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police officer|terrorist plot,http://www.imdb.com/title/tt1345836/?ref_=fn_tt_tt_1,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_tt_tt_1,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [555]:
old_data.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [556]:
old_data=old_data[['movie_title','title_year','genres','actor_1_name','actor_2_name','actor_3_name','director_name','plot_keywords']]

In [557]:
old_data.head()

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,plot_keywords
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,avatar|future|marine|native|paraplegic
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,goddess|marriage ceremony|marriage proposal|pirate|singapore
2,Spectre,2015.0,Action|Adventure|Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,bomb|espionage|sequel|spy|terrorist
3,The Dark Knight Rises,2012.0,Action|Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,deception|imprisonment|lawlessness|police officer|terrorist plot
4,Star Wars: Episode VII - The Force Awakens,NaN,Documentary,Doug Walker,Rob Walker,NaN,Doug Walker,NaN

In [558]:
old_data.isnull().sum()

movie_title        0
title_year       108
genres             0
actor_1_name       7
actor_2_name      13
actor_3_name      23
director_name    104
plot_keywords    153
dtype: int64

In [559]:
old_data[old_data.director_name.isnull()]

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,plot_keywords
177,Miami Vice,NaN,Action|Crime|Drama|Mystery|Thriller,Don Johnson,Philip Michael Thomas,John Diehl,NaN,cult tv|detective|drugs|police|undercover
260,The A-Team,NaN,Action|Adventure|Crime,George Peppard,Dirk Benedict,Dwight Schultz,NaN,1980s|cult tv|famous opening theme|good versus evil|hero for hire
404,Hannibal,NaN,Crime|Drama|Horror|Mystery|Thriller,Caroline Dhavernas,Scott Thompson,Hettienne Park,NaN,blood|cannibalism|fbi|manipulation|psychiatrist
459,Daredevil,NaN,Action|Adventure|Crime|Drama|Sci-Fi|Thriller,Elden Henson,Royce Johnson,Charlie Cox,NaN,corruption|lawyer|partnership|superhero|vigilante
479,Bewitched,NaN,Comedy|Family|Fantasy,Elizabeth Montgomery,Agnes Moorehead,Dick York,NaN,connecticut|magic|marriage|witch|witchcraft
...,...,...,...,...,...,...,...,...
4798,Heroes,NaN,Drama|Fantasy|Sci-Fi|Thriller,Sendhil Ramamurthy,Masi Oka,Greg Grunberg,NaN,father daughter relationship|serial killer|superhero|supernatural power|visi...
4803,Home Movies,NaN,Animation|Comedy|Drama,Brendon Small,Ron Lynch,Melissa Bardin Galsky,NaN,coach|friend|school|series|tv series
4819,Revolution,NaN,Action|Adventure|Drama|Sci-Fi,Billy Burke,Tracy Spiridakos,David Lyons,NaN,2020s|near future|one word series title|post apocalypse|year 2027
4869,Happy Valley,NaN,Crime|Drama,Shirley Henderson,James Norton,Sarah Lancashire,NaN,caravan|police|police sergeant|tied to a chair|yorkshire
5039,The Following,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,Valorie Curry,Sam Underwood,NaN,cult|fbi|hideout|prison escape|serial killer

In [560]:
old_data=old_data.replace(np.nan,'unknown')

In [561]:
old_data.rename(columns={'plot_keywords':'keywords'},inplace=True)

In [562]:
old_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_title    5043 non-null   object
 1   title_year     5043 non-null   object
 2   genres         5043 non-null   object
 3   actor_1_name   5043 non-null   object
 4   actor_2_name   5043 non-null   object
 5   actor_3_name   5043 non-null   object
 6   director_name  5043 non-null   object
 7   keywords       5043 non-null   object
dtypes: object(8)
memory usage: 315.3+ KB

In [563]:
old_data['keywords']

0                                 avatar|future|marine|native|paraplegic
1           goddess|marriage ceremony|marriage proposal|pirate|singapore
2                                    bomb|espionage|sequel|spy|terrorist
3       deception|imprisonment|lawlessness|police officer|terrorist plot
4                                                                unknown
                                      ...
5038                              fraud|postal worker|prison|theft|trial
5039                        cult|fbi|hideout|prison escape|serial killer
5040                                                             unknown
5041                                                             unknown
5042       actress name in title|crush|date|four word title|video camera
Name: keywords, Length: 5043, dtype: object

In [564]:
old_data['genres']=old_data['genres'].str.replace('|',' ')
old_data['keywords']=old_data['keywords'].str.replace('|',' ')

In [565]:
old_data['movie_title']=old_data['movie_title'].astype(str)

In [566]:
old_data

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
0,Avatar,2009,Action Adventure Fantasy Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,avatar future marine native paraplegic
1,Pirates of the Caribbean: At World's End,2007,Action Adventure Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,goddess marriage ceremony marriage proposal pirate singapore
2,Spectre,2015,Action Adventure Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,bomb espionage sequel spy terrorist
3,The Dark Knight Rises,2012,Action Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,deception imprisonment lawlessness police officer terrorist plot
4,Star Wars: Episode VII - The Force Awakens,unknown,Documentary,Doug Walker,Rob Walker,unknown,Doug Walker,unknown
...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,2013,Comedy Drama,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith,fraud postal worker prison theft trial
5039,The Following,unknown,Crime Drama Mystery Thriller,Natalie Zea,Valorie Curry,Sam Underwood,unknown,cult fbi hideout prison escape serial killer
5040,A Plague So Pleasant,2013,Drama Horror Thriller,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds,unknown
5041,Shanghai Calling,2012,Comedy Drama Romance,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia,unknown
5042,My Date with Drew,2004,Documentary,John August,Brian Herzlinger,Jon Gunn,Jon Gunn,actress name in title crush date four word title video camera

In [567]:
old_data['movie_title']=old_data['movie_title'].apply(lambda x : x[:-1])

In [568]:
old_data['keywords'].tail()

5038                           fraud postal worker prison theft trial
5039                     cult fbi hideout prison escape serial killer
5040                                                          unknown
5041                                                          unknown
5042    actress name in title crush date four word title video camera
Name: keywords, dtype: object

In [569]:
old_data

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
0,Avatar,2009,Action Adventure Fantasy Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,avatar future marine native paraplegic
1,Pirates of the Caribbean: At World's End,2007,Action Adventure Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,goddess marriage ceremony marriage proposal pirate singapore
2,Spectre,2015,Action Adventure Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,bomb espionage sequel spy terrorist
3,The Dark Knight Rises,2012,Action Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,deception imprisonment lawlessness police officer terrorist plot
4,Star Wars: Episode VII - The Force Awakens,unknown,Documentary,Doug Walker,Rob Walker,unknown,Doug Walker,unknown
...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,2013,Comedy Drama,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith,fraud postal worker prison theft trial
5039,The Following,unknown,Crime Drama Mystery Thriller,Natalie Zea,Valorie Curry,Sam Underwood,unknown,cult fbi hideout prison escape serial killer
5040,A Plague So Pleasant,2013,Drama Horror Thriller,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds,unknown
5041,Shanghai Calling,2012,Comedy Drama Romance,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia,unknown
5042,My Date with Drew,2004,Documentary,John August,Brian Herzlinger,Jon Gunn,Jon Gunn,actress name in title crush date four word title video camera

In [570]:
old_data

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
0,Avatar,2009,Action Adventure Fantasy Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,avatar future marine native paraplegic
1,Pirates of the Caribbean: At World's End,2007,Action Adventure Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,goddess marriage ceremony marriage proposal pirate singapore
2,Spectre,2015,Action Adventure Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,bomb espionage sequel spy terrorist
3,The Dark Knight Rises,2012,Action Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,deception imprisonment lawlessness police officer terrorist plot
4,Star Wars: Episode VII - The Force Awakens,unknown,Documentary,Doug Walker,Rob Walker,unknown,Doug Walker,unknown
...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,2013,Comedy Drama,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith,fraud postal worker prison theft trial
5039,The Following,unknown,Crime Drama Mystery Thriller,Natalie Zea,Valorie Curry,Sam Underwood,unknown,cult fbi hideout prison escape serial killer
5040,A Plague So Pleasant,2013,Drama Horror Thriller,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds,unknown
5041,Shanghai Calling,2012,Comedy Drama Romance,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia,unknown
5042,My Date with Drew,2004,Documentary,John August,Brian Herzlinger,Jon Gunn,Jon Gunn,actress name in title crush date four word title video camera

In [571]:
movie=pd.read_csv('../input/the-movies-dataset/movies_metadata.csv')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [572]:
movie.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lV...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his room until Andy's birthday bri...",21.9469,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 1075...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an enchanted board game that opens the...,17.0155,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 255...","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'França...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqg...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud between next-door neighbors and ...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for Love.,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the women are holding their breath, w...",3.85949,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,"[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself... and never let you forget it.,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Collection', 'poster_path': '/nts...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,"Just when George Banks has recovered from his daughter's wedding, he receive...",8.38752,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Touchstone Picture...","[{'iso_3166_1': 'US', 'name': 'United States of America'}]",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!,Father of the Bride Part II,False,5.7,173.0

In [573]:
movie.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [574]:
movie['tagline'][1:6]

1                                         Roll the dice and unleash the excitement!
2                              Still Yelling. Still Fighting. Still Ready for Love.
3    Friends are the people who let you be yourself... and never let you forget it.
4    Just When His World Is Back To Normal... He's In For The Surprise Of His Life!
5                                                          A Los Angeles Crime Saga
Name: tagline, dtype: object

In [575]:
movie['release_date']=pd.to_datetime(movie['release_date'],errors='coerce')

In [576]:
movie['release_date'].isnull().sum()

90

In [577]:
movie['title_year']=movie['release_date'].dt.year

In [578]:
movie=movie[['title','title_year','genres','id']]

In [579]:
movie=movie.loc[movie.title_year==2017]
movie.head()

,title,title_year,genres,id
26560,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 14, '...",166426
26561,Justice League,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, '...",141052
26565,Thor: Ragnarok,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, '...",284053
26566,Guardians of the Galaxy Vol. 2,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, '...",283995
30536,The King's Daughter,2017.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}, {'id': 12, 'na...",245842

In [580]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 532 entries, 26560 to 45465
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       532 non-null    object
 1   title_year  532 non-null    float64
 2   genres      532 non-null    object
 3   id          532 non-null    object
dtypes: float64(1), object(3)
memory usage: 20.8+ KB

In [581]:
movie['id']=movie['id'].astype(int)
credit=pd.read_csv('../input/the-movies-dataset/credits.csv')
key=pd.read_csv('../input/the-movies-dataset/keywords.csv')
key.head()

,id,keywords
0,862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, ..."
1,8844,"[{'id': 10090, 'name': 'board game'}, {'id': 10941, 'name': 'disappearance'}..."
2,15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392, 'name': 'best friend'}, {'id..."
3,31357,"[{'id': 818, 'name': 'based on novel'}, {'id': 10131, 'name': 'interracial r..."
4,11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'name': 'midlife crisis'}, {'id'..."

In [582]:
new_data=pd.merge(movie,credit,on='id')
new_data=pd.merge(new_data,key,on='id')

In [583]:
new_data.head()

,title,title_year,genres,id,cast,crew,keywords
0,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 14, '...",166426,"[{'cast_id': 1, 'character': 'Captain Jack Sparrow', 'credit_id': '52fe4c9cc...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'department': 'Production', 'gend...","[{'id': 658, 'name': 'sea'}, {'id': 3799, 'name': 'ship'}, {'id': 9663, 'nam..."
1,Justice League,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, '...",141052,"[{'cast_id': 2, 'character': 'Bruce Wayne / Batman', 'credit_id': '535e68db0...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'department': 'Production', 'gend...","[{'id': 849, 'name': 'dc comics'}, {'id': 9717, 'name': 'based on comic'}, {..."
2,Thor: Ragnarok,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, '...",284053,"[{'cast_id': 0, 'character': 'Thor Odinson', 'credit_id': '545d46a80e0a261fb...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'department': 'Writing', 'gender'...","[{'id': 8828, 'name': 'marvel comic'}, {'id': 9663, 'name': 'sequel'}, {'id'..."
3,Guardians of the Galaxy Vol. 2,2017.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, '...",283995,"[{'cast_id': 3, 'character': 'Peter Quill / Star-Lord', 'credit_id': '53dd76...","[{'credit_id': '59171547925141583c0315a6', 'department': 'Sound', 'gender': ...","[{'id': 9663, 'name': 'sequel'}, {'id': 9715, 'name': 'superhero'}, {'id': 9..."
4,The King's Daughter,2017.0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}, {'id': 12, 'na...",245842,"[{'cast_id': 0, 'character': 'King Louis XIV', 'credit_id': '5431dd580e0a265...","[{'credit_id': '5431de49c3a36825d300007e', 'department': 'Directing', 'gende...","[{'id': 4978, 'name': 'immortality'}, {'id': 5938, 'name': 'mermaid'}, {'id'..."

In [584]:
from ast import literal_eval
cols=['genres','cast','crew','keywords']
for col in cols:
    new_data[col]=new_data[col].apply(literal_eval)

In [585]:
def get_genre(x):
    gen=[]
    for i in x:
        if i['name']=='Science Fiction':
            name='Sci-Fi'
            gen.append(name)
        else:
            gen.append(i['name'])
    if gen==[]:
        return []
    else:
        return ' '.join(gen)

In [586]:
new_data['genres']=new_data['genres'].apply(get_genre)

In [587]:
new_data['cast'][0]

[{'cast_id': 1,
  'character': 'Captain Jack Sparrow',
  'credit_id': '52fe4c9cc3a36847f8236a53',
  'gender': 2,
  'id': 85,
  'name': 'Johnny Depp',
  'order': 0,
  'profile_path': '/kbWValANhZI8rbWZXximXuMN4UN.jpg'},
 {'cast_id': 9,
  'character': 'Captain Armando Salazar',
  'credit_id': '54db4949c3a368122d0017fe',
  'gender': 2,
  'id': 3810,
  'name': 'Javier Bardem',
  'order': 1,
  'profile_path': '/grBOK7Ep09JBE3H5LyV5JaZZ1XZ.jpg'},
 {'cast_id': 16,
  'character': 'Captain Hector Barbossa',
  'credit_id': '54e44e5ec3a368454b00a02f',
  'gender': 2,
  'id': 118,
  'name': 'Geoffrey Rush',
  'order': 2,
  'profile_path': '/5h91WHSK80YtqTk1bMiar2IZzO2.jpg'},
 {'cast_id': 7,
  'character': 'Henry Turner',
  'credit_id': '54db49359251415a0d0012a0',
  'gender': 2,
  'id': 1017347,
  'name': 'Brenton Thwaites',
  'order': 3,
  'profile_path': '/dM0m0OxREfW4HxwV2qQeitS8dfO.jpg'},
 {'cast_id': 8,
  'character': 'Carina Smyth',
  'credit_id': '54db493e925141618f00189a',
  'gender': 1,
  'id': 115150,
  'name': 'Kaya Scodelario',
  'order': 4,
  'profile_path': '/iTrPnn7oS96k0iWPzNxaKCNutB6.jpg'},
 {'cast_id': 14,
  'character': 'Joshamee Gibbs',
  'credit_id': '54e44e31c3a368087b004b56',
  'gender': 2,
  'id': 2449,
  'name': 'Kevin McNally',
  'order': 5,
  'profile_path': '/fIJF3TZn8ckHkcl44oX77GvPv9e.jpg'},
 {'cast_id': 15,
  'character': 'Scrum',
  'credit_id': '54e44e4fc3a3684897002c08',
  'gender': 2,
  'id': 1115,
  'name': 'Stephen Graham',
  'order': 6,
  'profile_path': '/81VZiCA6w8nXG0UjqXCgSJare5N.jpg'},
 {'cast_id': 28,
  'character': 'Scarfield',
  'credit_id': '57f68ea49251413616007300',
  'gender': 2,
  'id': 1371,
  'name': 'David Wenham',
  'order': 7,
  'profile_path': '/xDUXLTF5i2fYx7eSEAR3IdaUb9y.jpg'},
 {'cast_id': 13,
  'character': 'Shansa',
  'credit_id': '54e44e0cc3a3685756009e87',
  'gender': 1,
  'id': 229932,
  'name': 'Golshifteh Farahani',
  'order': 8,
  'profile_path': '/lbsd2lAIQq4egOUXDIfjhte12vv.jpg'},
 {'cast_id': 17,
  'character': 'Will Turner',
  'credit_id': '554768e292514119e00065f8',
  'gender': 2,
  'id': 114,
  'name': 'Orlando Bloom',
  'order': 9,
  'profile_path': '/kKWJlX2tcjqceSfUxnV7Jle5Kt.jpg'},
 {'cast_id': 18,
  'character': 'Marty',
  'credit_id': '554769499251411147001bcb',
  'gender': 2,
  'id': 4030,
  'name': 'Martin Klebba',
  'order': 10,
  'profile_path': '/amlhUrXQ7t1NEPajdj2dQdbC0rt.jpg'},
 {'cast_id': 23,
  'character': 'Mullroy',
  'credit_id': '57e2922bc3a36808b900c1a3',
  'gender': 2,
  'id': 1714,
  'name': 'Angus Barnett',
  'order': 11,
  'profile_path': '/usYsWRccdM4Y00RycsQFFOdNVe.jpg'},
 {'cast_id': 19,
  'character': 'Cremble',
  'credit_id': '55476961c3a3680ce80091da',
  'gender': 0,
  'id': 1193833,
  'name': 'Adam Brown',
  'order': 12,
  'profile_path': '/54iHvIA8ZTNfvKpb2ZxRY73A5MZ.jpg'},
 {'cast_id': 38,
  'character': 'Bollard',
  'credit_id': '57f68ea7925141360100754f',
  'gender': 0,
  'id': 1355191,
  'name': 'Danny Kirrane',
  'order': 13,
  'profile_path': '/vn4NIHMJb0Sf39MOP3cgMdk2N8h.jpg'},
 {'cast_id': 22,
  'character': 'Murtogg',
  'credit_id': '57e29210c3a3680a110056ca',
  'gender': 0,
  'id': 1713,
  'name': 'Giles New',
  'order': 14,
  'profile_path': '/e0Ap9fkLAFcxLVHpK8KH2TQV3wI.jpg'},
 {'cast_id': 84,
  'character': 'Pike',
  'credit_id': '591f7a46c3a368723d03b63b',
  'gender': 0,
  'id': 1819920,
  'name': 'Delroy Atkinson',
  'order': 15,
  'profile_path': '/XcMnuXUPLNYzRL58s5TKPUFq2g.jpg'},
 {'cast_id': 21,
  'character': 'Uncle Jack',
  'credit_id': '57e291cf92514118f700625d',
  'gender': 2,
  'id': 10215,
  'name': 'Paul McCartney',
  'order': 16,
  'profile_path': '/v7FagbD9EY4MVUtcrk9ESjPWV7q.jpg'},
 {'cast_id': 43,
  'character': 'Elizabeth Swann',
  'credit_id': '58f708cf9251415dec00953a',
  'gender': 1,
  'id': 116,
  'name': 'Keira Knightley',
  'order': 17,
  'profile_path': '/rv6quYbTgFTmBAoePwy5xuurW3g.jpg'},
 {'cast_id': 91,
  'character': 'Young Jack Sparrow',
  'credit_id': '59338b3dc3a3685a35016ca6',
  'gender': 0,
  'id': 1772106,
  'name': 'Anthony De La Torre',
  'order': 18,
  'profile_path': '/sgtspl6fcAuhPo4wKYkzlzSgvmg.jpg'},
 {'cast_id': 92,
  'character': 'Young Henry Turner',
  'credit_id': '59338b66c3a36859de01633a',
  'gender': 2,
  'id': 1828139,
  'name': 'Lewis McGowan',
  'order': 19,
  'profile_path': '/27pyhArCRR8ZqIyiak9c0N0l1nz.jpg'},
 {'cast_id': 85,
  'character': 'Lieutenant Lesaro',
  'credit_id': '591f7a8cc3a368799b037a0a',
  'gender': 2,
  'id': 1089049,
  'name': 'Juan Carlos Vellido',
  'order': 20,
  'profile_path': '/m1GEfFgcDNPTCTGUhrita7d5ec1.jpg'},
 {'cast_id': 86,
  'character': 'Officer Madga',
  'credit_id': '591f7acc925141482f039128',
  'gender': 0,
  'id': 1530814,
  'name': 'Rodney Afif',
  'order': 21,
  'profile_path': '/wr1gTOcRcyKO4fYlUwsPLRlP7bn.jpg'},
 {'cast_id': 87,
  'character': 'Mayor Dix',
  'credit_id': '591f7ae1c3a3687a64039857',
  'gender': 2,
  'id': 27752,
  'name': 'Bruce Spence',
  'order': 22,
  'profile_path': '/pwJJBmO9MG3OxVX9efGrB6BTFyw.jpg'},
 {'cast_id': 31,
  'character': "Mayor's Wife",
  'credit_id': '57f68ea5c3a3681607006e8c',
  'gender': 1,
  'id': 61914,
  'name': 'Zoe Ventoura',
  'order': 23,
  'profile_path': '/fMBiXCtCTqpEmjAfTVC3NssVMCk.jpg'},
 {'cast_id': 33,
  'character': 'Maddox',
  'credit_id': '57f68ea6c3a3681607006e8e',
  'gender': 2,
  'id': 1112872,
  'name': 'James Mackay',
  'order': 24,
  'profile_path': '/nJPYaP94wXwh1bYnFzkQh1BB30l.jpg'},
 {'cast_id': 51,
  'character': 'Upper Class Lady',
  'credit_id': '591293c59251414edb04e228',
  'gender': 1,
  'id': 1813772,
  'name': 'Brooke Chamberlain',
  'order': 25,
  'profile_path': '/vYqTEUUY4EG6jPzP5wnZNhy4aAy.jpg'},
 {'cast_id': 45,
  'character': 'Young Captain Teague',
  'credit_id': '5912926dc3a368646b0521a2',
  'gender': 2,
  'id': 16811,
  'name': 'Alexander Scheer',
  'order': 26,
  'profile_path': '/f6eWj5VEMBb3O3aviqgMoujM3kf.jpg'},
 {'cast_id': 32,
  'character': 'Pirate Broom',
  'credit_id': '57f68ea5925141360d007429',
  'gender': 0,
  'id': 61784,
  'name': 'Goran D. Kleut',
  'order': 27,
  'profile_path': '/ikAVxzlgo4bXQWn4GpoFfDrgnth.jpg'},
 {'cast_id': 40,
  'character': 'Pirate',
  'credit_id': '57f68ea892514136130074b0',
  'gender': 0,
  'id': 1535048,
  'name': 'Wassim Hawat',
  'order': 28,
  'profile_path': '/yTJCBoDa1OKt7h6JDKYaZnlLqeA.jpg'},
 {'cast_id': 37,
  'character': 'British Executioner',
  'credit_id': '57f68ea7925141360100754d',
  'gender': 0,
  'id': 1394235,
  'name': "Ben O'Toole",
  'order': 29,
  'profile_path': '/f9cCCp1PlRZo4sWdwppHTeOC8kZ.jpg'},
 {'cast_id': 42,
  'character': 'Young Pirate Jeff',
  'credit_id': '57f68ea8c3a368161c007391',
  'gender': 2,
  'id': 1690240,
  'name': 'Finn Ireland',
  'order': 30,
  'profile_path': '/x1IZJZLFHboPhZbdycZcNo2kZoM.jpg'},
 {'cast_id': 44,
  'character': 'Spanish Officer',
  'credit_id': '59129248c3a36864ec048639',
  'gender': 0,
  'id': 1414764,
  'name': 'Nico Cortez',
  'order': 31,
  'profile_path': '/ujk9vAlutbLUe9VbjPE6RDuQqVC.jpg'},
 {'cast_id': 49,
  'character': 'Young Greenhorn',
  'credit_id': '591293549251414eca04accf',
  'gender': 0,
  'id': 1394227,
  'name': 'James Fraser',
  'order': 32,
  'profile_path': '/4lcpUIRwFVmPkkxUvYdUNSQQddc.jpg'},
 {'cast_id': 115,
  'character': 'Woman',
  'credit_id': '59c783a3c3a368140305a3f1',
  'gender': 0,
  'id': 1499792,
  'name': 'Derani Scarr',
  'order': 33,
  'profile_path': '/aob0mfWTaJaUlHDVef2dA7Dlwhc.jpg'},
 {'cast_id': 93,
  'character': 'Grimes',
  'credit_id': '5999d18a9251414a18001dd4',
  'gender': 0,
  'id': 126200,
  'name': 'Robert Morgan',
  'order': 34,
  'profile_path': '/8sFiiilQmp2jvLKn6h5QPchA5Gq.jpg'},
 {'cast_id': 94,
  'character': 'Pirate with Broom',
  'credit_id': '59a67afe9251411293009e0c',
  'gender': 0,
  'id': 61784,
  'name': 'Goran D. Kleut',
  'order': 35,
  'profile_path': '/ikAVxzlgo4bXQWn4GpoFfDrgnth.jpg'},
 {'cast_id': 29,
  'character': 'Spanish Soldier',
  'credit_id': '57f68ea5925141360100754a',
  'gender': 2,
  'id': 1386458,
  'name': 'Mahesh Jadu',
  'order': 36,
  'profile_path': '/gfcZiYji4x3tjGQq7vTK8goz40D.jpg'},
 {'cast_id': 34,
  'character': 'British Soldier',
  'credit_id': '57f68ea692514136130074ae',
  'gender': 0,
  'id': 1394427,
  'name': 'Travis Jeffery',
  'order': 37,
  'profile_path': '/lOR40uoh60aKx3ORArhKBQAaBO6.jpg'},
 {'cast_id': 111,
  'character': 'British Soldier',
  'credit_id': '59c77df0c3a36813ed057ad8',
  'gender': 0,
  'id': 1205492,
  'name': 'Akos Armont',
  'order': 38,
  'profile_path': '/t0nRw07H8aXtzz7az5yjDSZwVVg.jpg'},
 {'cast_id': 104,
  'character': 'British Soldier',
  'credit_id': '59c6c742c3a368141e044fa3',
  'gender': 0,
  'id': 1533328,
  'name': 'Sean Lynch',
  'order': 39,
  'profile_path': '/m8Q9SaYTWJ5iXLoS2E4zvcD4tQ1.jpg'},
 {'cast_id': 95,
  'character': 'British Soldier',
  'credit_id': '59a67b84c3a36827990085f8',
  'gender': 0,
  'id': 1394235,
  'name': "Ben O'Toole",
  'order': 40,
  'profile_path': '/f9cCCp1PlRZo4sWdwppHTeOC8kZ.jpg'},
 {'cast_id': 105,
  'character': 'CG Ghost Soldier',
  'credit_id': '59c6c7d69251415b32049e77',
  'gender': 0,
  'id': 1893668,
  'name': 'Akshay Caplash',
  'order': 41,
  'profile_path': '/s3QTX4IdN3wUNN9YiZBid2ANhmM.jpg'},
 {'cast_id': 106,
  'character': 'CG Ghost Soldier',
  'credit_id': '59c6c8629251415b6e047778',
  'gender': 2,
  'id': 1893671,
  'name': 'Rafael Torrijos',
  'order': 42,
  'profile_path': '/lro1QSBv5cmkiO8R8RbxADGXIka.jpg'},
 {'cast_id': 112,
  'character': 'CG Ghost Soldier',
  'credit_id': '59c7805d9251415b87053e7f',
  'gender': 0,
  'id': 1893872,
  'name': 'Mivon Prince-Leyva',
  'order': 43,
  'profile_path': '/c5CfJBn3B0Ce07TxgPUx9ttUTLv.jpg'},
 {'cast_id': 110,
  'character': 'First Officer Wade',
  'credit_id': '59c77d9cc3a3681454052a75',
  'gender': 2,
  'id': 76068,
  'name': 'Michael Dorman',
  'order': 44,
  'profile_path': '/95hvX99zyHIpHJ9Ajv35TWgNlGN.jpg'},
 {'cast_id': 116,
  'character': 'Officer Cole',
  'credit_id': '59c784a99251415b870541ed',
  'gender': 2,
  'id': 33184,
  'name': 'Rohan Nichol',
  'order': 45,
  'profile_path': '/nzvL3MRpADYWlH4ppyYgmCnM1kZ.jpg'},
 {'cast_id': 96,
  'character': 'Officer Santos',
  'credit_id': '59c6b999c3a368144304be34',
  'gender': 0,
  'id': 1893640,
  'name': 'Rupert Raineri',
  'order': 46,
  'profile_path': '/oXeONe2M6qwiVlDFpJIT1wrA9Ek.jpg'},
 {'cast_id': 97,
  'character': 'Officer Moss',
  'credit_id': '59c6b9fec3a368143004b954',
  'gender': 0,
  'id': 1893641,
  'name': 'Stephen Lopez',
  'order': 47,
  'profile_path': '/hYoItjKNWnncBbjM3voLEu5DnN8.jpg'},
 {'cast_id': 109,
  'character': 'Captain Toms',
  'credit_id': '59c77d659251415b5d05482d',
  'gender': 0,
  'id': 75744,
  'name': 'Richard Piper',
  'order': 48,
  'profile_path': '/3SEI2j8jIzVthrYifpMgjNC4MHp.jpg'},
 {'cast_id': 98,
  'character': 'Mr. Krill',
  'credit_id': '59c6bc1dc3a368140304c936',
  'gender': 0,
  'id': 1347909,
  'name': 'Justin Smith',
  'order': 49,
  'profile_path': '/7knG8VrDuEmhAZT2B4p1zmMjDJy.jpg'},
 {'cast_id': 99,
  'character': 'Mr. Swift',
  'credit_id': '59c6be5f9251415b2804b325',
  'gender': 0,
  'id': 1486057,
  'name': 'John Leary',
  'order': 50,
  'profile_path': '/bCP5mcXgFp5X7mq7jTmYpmBbtHE.jpg'},
 {'cast_id': 100,
  'character': 'Bowen',
  'credit_id': '59c6c070c3a368141e0448fa',
  'gender': 0,
  'id': 1014587,
  'name': 'Bryan Probets',
  'order': 51,
  'profile_path': '/wp0o01OuR5YF3DWjBBUYAWUbzHA.jpg'},
 {'cast_id': 113,
  'character': 'Pig Kelly',
  'credit_id': '59c7810a9251415b240582b0',
  'gender': 2,
  'id': 57904,
  'name': 'Ken Radley',
  'order': 52,
  'profile_path': '/jqiM2DbXtNRF3yxRaU2nkYzewEJ.jpg'},
 {'cast_id': 101,
  'character': 'Beatrice',
  'credit_id': '59c6c14bc3a36813ed04aed4',
  'gender': 1,
  'id': 1252521,
  'name': 'Hannah Walters',
  'order': 53,
  'profile_path': '/3hUokXHcRhdpM971cb3kbaVSrY8.jpg'},
 {'cast_id': 114,
  'character': 'Priest',
  'credit_id': '59c7826c9251415b32055db4',
  'gender': 0,
  'id': 1545346,
  'name': 'Jonathan Elsom',
  'order': 54,
  'profile_path': '/i1LEAdB5y6zg4lVa01hV9ZZo7Ew.jpg'},
 {'cast_id': 102,
  'character': 'Captain Morgan',
  'credit_id': '59c6c217c3a3681454046e90',
  'gender': 2,
  'id': 143328,
  'name': 'K. Todd Freeman',
  'order': 55,
  'profile_path': '/2L7Qh4hA2dsCIPZAVfgerax7i2q.jpg'},
 {'cast_id': 107,
  'character': 'Jail Guard',
  'credit_id': '59c6c957c3a368140304d946',
  'gender': 0,
  'id': 1893677,
  'name': 'James Lawson',
  'order': 56,
  'profile_path': '/gtcdsTruLPzpL2xJhePsOq38LjX.jpg'},
 {'cast_id': 108,
  'character': "Uncle Jack's Cellmate",
  'credit_id': '59c6ca34c3a3681461041481',
  'gender': 0,
  'id': 1216570,
  'name': 'Darcy Laurie',
  'order': 57,
  'profile_path': '/bTZgOB4wl4ECbHiGjoKQAQdvTUW.jpg'},
 {'cast_id': 30,
  'character': 'Townswoman (uncredited)',
  'credit_id': '57f68ea592514172c5002e01',
  'gender': 1,
  'id': 1255055,
  'name': 'Jessica Green',
  'order': 58,
  'profile_path': '/7l3bkNv92uii8im5B4vyF0ABgcS.jpg'},
 {'cast_id': 52,
  'character': 'Townswoman (uncredited)',
  'credit_id': '591294019251414e8504da81',
  'gender': 0,
  'id': 1345090,
  'name': 'Haley Madison',
  'order': 59,
  'profile_path': '/3XJGp5oJCGvqosOhSSgQZWI8cKo.jpg'},
 {'cast_id': 36,
  'character': 'Townschild (uncredited)',
  'credit_id': '57f68ea7c3a36816250071ea',
  'gender': 0,
  'id': 1632129,
  'name': 'Kiara Freeman',
  'order': 60,
  'profile_path': '/3n5EDxHBritMzqxIS47A6Qccg74.jpg'},
 {'cast_id': 35,
  'character': 'Townschild (uncredited)',
  'credit_id': '57f68ea6c3a3681604007202',
  'gender': 0,
  'id': 1690237,
  'name': 'Piper Nairn',
  'order': 61,
  'profile_path': '/cOVpgx5JF9XeFUF2am9Bk4f5wkh.jpg'},
 {'cast_id': 53,
  'character': 'Townsperson (uncredited)',
  'credit_id': '5912942ec3a36864c604d3d7',
  'gender': 1,
  'id': 1692989,
  'name': 'Suzanne Dervish-Ali',
  'order': 62,
  'profile_path': '/7OQgHuuzFbtO9jAF4w6zcuzqmAK.jpg'},
 {'cast_id': 50,
  'character': 'Townsperson (uncredited)',
  'credit_id': '591293a5c3a368650a04aff2',
  'gender': 0,
  'id': 1813771,
  'name': 'Donnie Baxter',
  'order': 63,
  'profile_path': '/dm2cSQwySnOj9sWqca9nBspS8sL.jpg'},
 {'cast_id': 41,
  'character': 'Maid (uncredited)',
  'credit_id': '57f68ea8925141360300747b',
  'gender': 0,
  'id': 1690239,
  'name': 'Winnie Mzembe',
  'order': 64,
  'profile_path': '/lUTozzeBvTZZkpUQLE5V5baS12X.jpg'},
 {'cast_id': 39,
  'character': 'Greenwich Village Upper Class Lady (uncredited)',
  'credit_id': '57f68ea892514172c5002e04',
  'gender': 0,
  'id': 1690238,
  'name': 'Christie-Lee Britten',
  'order': 65,
  'profile_path': '/uNSjA73XjDbQMJB1XGnoKB89zux.jpg'},
 {'cast_id': 48,
  'character': 'Twin Middle Class Lady (uncredited)',
  'credit_id': '5912932f9251414e8904ee64',
  'gender': 0,
  'id': 1813770,
  'name': 'Mollie McGregor',
  'order': 66,
  'profile_path': '/q4XZ9rV1TbrsqvK91a9FAMudL6C.jpg'},
 {'cast_id': 103,
  'character': 'Twin Middle Class Lady (uncredited)',
  'credit_id': '59c6c5399251415b6e0473ea',
  'gender': 0,
  'id': 1571654,
  'name': 'Sophia McGregor',
  'order': 67,
  'profile_path': '/egbKVmd3f1xgAq90vDiRLLZIFXx.jpg'}]

In [588]:
def get_cast1(x):
    if isinstance(x,list):
        names=[i['name'] for i in x]
        if names==[]:
            return []
        else :
            return names[0]


        
def get_cast2(x):
    if isinstance(x,list):
        names=[i['name'] for i in x]
        if len(names)<=1:
            return []
        else :
            return names[1]
        
def get_cast3(x):
    if isinstance(x,list):
        names=[i['name'] for i in x]
        if len(names)<=2:
            return []
        else :
            return names[2]

In [589]:
new_data['actor_1_name']=new_data['cast'].apply(get_cast1)
new_data['actor_2_name']=new_data['cast'].apply(get_cast2)

new_data['actor_3_name']=new_data['cast'].apply(get_cast3)

In [590]:
new_data.head()

,title,title_year,genres,id,cast,crew,keywords,actor_1_name,actor_2_name,actor_3_name
0,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,Adventure Action Fantasy Comedy,166426,"[{'cast_id': 1, 'character': 'Captain Jack Sparrow', 'credit_id': '52fe4c9cc...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'department': 'Production', 'gend...","[{'id': 658, 'name': 'sea'}, {'id': 3799, 'name': 'ship'}, {'id': 9663, 'nam...",Johnny Depp,Javier Bardem,Geoffrey Rush
1,Justice League,2017.0,Action Adventure Fantasy Sci-Fi,141052,"[{'cast_id': 2, 'character': 'Bruce Wayne / Batman', 'credit_id': '535e68db0...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'department': 'Production', 'gend...","[{'id': 849, 'name': 'dc comics'}, {'id': 9717, 'name': 'based on comic'}, {...",Ben Affleck,Henry Cavill,Gal Gadot
2,Thor: Ragnarok,2017.0,Action Adventure Fantasy Sci-Fi,284053,"[{'cast_id': 0, 'character': 'Thor Odinson', 'credit_id': '545d46a80e0a261fb...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'department': 'Writing', 'gender'...","[{'id': 8828, 'name': 'marvel comic'}, {'id': 9663, 'name': 'sequel'}, {'id'...",Chris Hemsworth,Tom Hiddleston,Cate Blanchett
3,Guardians of the Galaxy Vol. 2,2017.0,Action Adventure Comedy Sci-Fi,283995,"[{'cast_id': 3, 'character': 'Peter Quill / Star-Lord', 'credit_id': '53dd76...","[{'credit_id': '59171547925141583c0315a6', 'department': 'Sound', 'gender': ...","[{'id': 9663, 'name': 'sequel'}, {'id': 9715, 'name': 'superhero'}, {'id': 9...",Chris Pratt,Zoe Saldana,Dave Bautista
4,The King's Daughter,2017.0,Fantasy Action Adventure,245842,"[{'cast_id': 0, 'character': 'King Louis XIV', 'credit_id': '5431dd580e0a265...","[{'credit_id': '5431de49c3a36825d300007e', 'department': 'Directing', 'gende...","[{'id': 4978, 'name': 'immortality'}, {'id': 5938, 'name': 'mermaid'}, {'id'...",Pierce Brosnan,William Hurt,Benjamin Walker

In [591]:
def director(x):
    name=[]
    for i in x:
        if i['job']=='Director':
            name=i['name']
    if name==[]:
        return []
    return name

In [592]:
new_data['director_name']=new_data['crew'].apply(director)

In [593]:
def get_keyword(x):
        names=[i['name'] for i in x]
        return ' '.join(names)

In [594]:
new_data['keys']=new_data['keywords'].apply(get_keyword)

In [595]:
new_data.head()

,title,title_year,genres,id,cast,crew,keywords,actor_1_name,actor_2_name,actor_3_name,director_name,keys
0,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,Adventure Action Fantasy Comedy,166426,"[{'cast_id': 1, 'character': 'Captain Jack Sparrow', 'credit_id': '52fe4c9cc...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'department': 'Production', 'gend...","[{'id': 658, 'name': 'sea'}, {'id': 3799, 'name': 'ship'}, {'id': 9663, 'nam...",Johnny Depp,Javier Bardem,Geoffrey Rush,Espen Sandberg,sea ship sequel artifact treasure map pirate period drama monkey swashbuckle...
1,Justice League,2017.0,Action Adventure Fantasy Sci-Fi,141052,"[{'cast_id': 2, 'character': 'Bruce Wayne / Batman', 'credit_id': '535e68db0...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'department': 'Production', 'gend...","[{'id': 849, 'name': 'dc comics'}, {'id': 9717, 'name': 'based on comic'}, {...",Ben Affleck,Henry Cavill,Gal Gadot,Zack Snyder,dc comics based on comic super powers dc extended universe
2,Thor: Ragnarok,2017.0,Action Adventure Fantasy Sci-Fi,284053,"[{'cast_id': 0, 'character': 'Thor Odinson', 'credit_id': '545d46a80e0a261fb...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'department': 'Writing', 'gender'...","[{'id': 8828, 'name': 'marvel comic'}, {'id': 9663, 'name': 'sequel'}, {'id'...",Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Taika Waititi,marvel comic sequel superhero based on comic female villain norse mythology ...
3,Guardians of the Galaxy Vol. 2,2017.0,Action Adventure Comedy Sci-Fi,283995,"[{'cast_id': 3, 'character': 'Peter Quill / Star-Lord', 'credit_id': '53dd76...","[{'credit_id': '59171547925141583c0315a6', 'department': 'Sound', 'gender': ...","[{'id': 9663, 'name': 'sequel'}, {'id': 9715, 'name': 'superhero'}, {'id': 9...",Chris Pratt,Zoe Saldana,Dave Bautista,James Gunn,sequel superhero based on comic misfit space outer space aftercreditsstinger...
4,The King's Daughter,2017.0,Fantasy Action Adventure,245842,"[{'cast_id': 0, 'character': 'King Louis XIV', 'credit_id': '5431dd580e0a265...","[{'credit_id': '5431de49c3a36825d300007e', 'department': 'Directing', 'gende...","[{'id': 4978, 'name': 'immortality'}, {'id': 5938, 'name': 'mermaid'}, {'id'...",Pierce Brosnan,William Hurt,Benjamin Walker,Sean McNamara,immortality mermaid period drama illegitimate child quest

In [596]:
new_data.drop(['cast','crew','id','keywords'],inplace=True,axis=1)

In [597]:
new_data.columns

Index(['title', 'title_year', 'genres', 'actor_1_name', 'actor_2_name',
       'actor_3_name', 'director_name', 'keys'],
      dtype='object')

In [598]:
old_data.columns

Index(['movie_title', 'title_year', 'genres', 'actor_1_name', 'actor_2_name',
       'actor_3_name', 'director_name', 'keywords'],
      dtype='object')

In [599]:
new_data.rename(columns={'title':'movie_title','keys':'keywords'},inplace=True)
new_data['title_year']=new_data['title_year'].astype(int).astype(str)

In [600]:
old_data.head()

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
0,Avatar,2009,Action Adventure Fantasy Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,avatar future marine native paraplegic
1,Pirates of the Caribbean: At World's End,2007,Action Adventure Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,goddess marriage ceremony marriage proposal pirate singapore
2,Spectre,2015,Action Adventure Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,bomb espionage sequel spy terrorist
3,The Dark Knight Rises,2012,Action Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,deception imprisonment lawlessness police officer terrorist plot
4,Star Wars: Episode VII - The Force Awakens,unknown,Documentary,Doug Walker,Rob Walker,unknown,Doug Walker,unknown

In [601]:
data=old_data.append(new_data)
data.shape

(5575, 8)

In [602]:
data.head()

,movie_title,title_year,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
0,Avatar,2009,Action Adventure Fantasy Sci-Fi,CCH Pounder,Joel David Moore,Wes Studi,James Cameron,avatar future marine native paraplegic
1,Pirates of the Caribbean: At World's End,2007,Action Adventure Fantasy,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski,goddess marriage ceremony marriage proposal pirate singapore
2,Spectre,2015,Action Adventure Thriller,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes,bomb espionage sequel spy terrorist
3,The Dark Knight Rises,2012,Action Thriller,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan,deception imprisonment lawlessness police officer terrorist plot
4,Star Wars: Episode VII - The Force Awakens,unknown,Documentary,Doug Walker,Rob Walker,unknown,Doug Walker,unknown

In [603]:
data.to_csv('Movies_upto_2017.csv',index=False)

In [604]:
df1.tail()

,movie_title,genres,keywords,director_name,actor_1_name,actor_2_name,actor_3_name
263,Holmes & Watson,Mystery Adventure Comedy Crime,england judge titanic albert einstein clue pipe smoking queen victoria victo...,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
264,Vice,Thriller Science Fiction Action Adventure,artificial intelligence android self-awareness mercenary virtual reality cop...,Adam McKay,Christian Bale,Amy Adams,Steve Carell
265,On the Basis of Sex,Drama History,judge 1970s biography supreme court based on a true story lawyer justice har...,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
266,Destroyer,Thriller Crime Drama Action,gang undercover cop interrogation policewoman teenage daughter lapd downward...,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
267,Black Mirror: Bandersnatch,Science Fiction Mystery Drama Thriller TV Movie,video game technology british choice free will british noir tech noir progra...,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [605]:
!pip install tmdbv3api
from tmdbv3api import TMDb
import json
import requests

Requirement already satisfied: tmdbv3api in /opt/conda/lib/python3.7/site-packages (1.6.1)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from tmdbv3api) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->tmdbv3api) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->tmdbv3api) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->tmdbv3api) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests->tmdbv3api) (3.0.4)

In [606]:
tmdb=TMDb()
tmdb.api_key='83cf022ec205972d97571d13de6d4b02'
from tmdbv3api import Movie

In [607]:
film=Movie()
def get_genre(x):
    genre=[]
    res=film.search(x)
    id=res[0].id
    response=requests.get('https://api.themoviedb.org/3/movie/{}?api_key=83cf022ec205972d97571d13de6d4b02'.format(id))
    data=response.json()
    for i in range(0,len(data['genres'])):
          genre.append(data['genres'][i]['name'])      
    return ' '.join(genre)

def get_keyword(x):
    key=[]
    res=film.search(x)
    key=list(film.keywords(res[0].id))
    return ' '.join(str(i) for i in key)

In [608]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (director)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [609]:
def actor1(x):
    return (x.split("screenplay); ")[-1].split(", ")[0])

def actor2(x):
    if len(x.split("screenplay); ")[-1].split(", "))<2:
        return np.nan
    else:
        return (x.split("screenplay); ")[-1].split(", ")[1])
    
def actor3(x):
    if len(x.split("screenplay); ")[-1].split(", "))<3:
        return np.nan
    else:
        return (x.split("screenplay); ")[-1].split(", ")[2])

In [610]:
def prepare(df):
    df['genres']=df['Title'].apply(get_genre)
    df['keywords']=df['Title'].apply(get_keyword)
    df['director_name']=df['Cast and crew'].apply(get_director)
    df['actor_1_name']=df['Cast and crew'].apply(actor1)
    df['actor_2_name']=df['Cast and crew'].apply(actor2)
    df['actor_3_name']=df['Cast and crew'].apply(actor3)
    df.drop(['Opening','Opening.1','Production company','Cast and crew','Ref.'],axis=1,inplace=True)
    df.rename(columns={'Title':'movie_title'},inplace=True)
    return df

In [611]:
link='https://en.wikipedia.org/wiki/List_of_American_films_of_2018'

In [612]:
df1=pd.read_html(link,header=0)[2]
df2=pd.read_html(link,header=0)[3]
df3=pd.read_html(link,header=0)[4]
df4=pd.read_html(link,header=0)[5]
df1=df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [613]:
link2='https://en.wikipedia.org/wiki/List_of_American_films_of_2019'

In [614]:
df5=pd.read_html(link2,header=0)[3]
df6=pd.read_html(link2,header=0)[4]
df7=pd.read_html(link2,header=0)[5]
df8=pd.read_html(link2,header=0)[6]
df5=df5.append(df6.append(df7.append(df8,ignore_index=True),ignore_index=True),ignore_index=True)
df5.shape

(241, 6)

In [615]:
data_18=prepare(df1)
data_19=prepare(df5)

In [616]:
data_18.to_csv('Movies_2018.csv',index=False)
data_19.to_csv('Movies_2019.csv',index=False)

In [617]:
data_18=data_18.append(data_19)
data_18.shape

(509, 7)

In [618]:
old_data.shape,new_data.shape

((5043, 8), (532, 8))

In [619]:
data_18.columns

Index(['movie_title', 'genres', 'keywords', 'director_name', 'actor_1_name',
       'actor_2_name', 'actor_3_name'],
      dtype='object')

In [620]:
old_data.columns

Index(['movie_title', 'title_year', 'genres', 'actor_1_name', 'actor_2_name',
       'actor_3_name', 'director_name', 'keywords'],
      dtype='object')

In [621]:
old_data.drop('title_year',axis=1,inplace=True)

In [622]:
old_data=old_data.append(data_18,ignore_index=True)
old_data.tail()

,movie_title,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
5547,Little Women,Drama Romance,Saoirse Ronan,Emma Watson,Florence Pugh,Greta Gerwig,usa sibling relationship based on novel or book massachusetts sister remake ...
5548,1917,War Drama Action History,George MacKay,Dean-Charles Chapman,Mark Strong,Sam Mendes,world war i british army race against time soldier trenches 1910s trench war...
5549,Just Mercy,Drama Crime,Michael B. Jordan,Jamie Foxx,Brie Larson,Destin Daniel Cretton,judge innocence based on a true story lawyer racism justice 1980s 20th century
5550,Clemency,Drama,Alfre Woodard,Wendell Pierce,Aldis Hodge,Chinonye Chukwu,prison death row prison warden woman director
5551,Apparition,Horror Thriller,Mena Suvari,Kevin Pollak,NaN,Waymon Boone,experiment supernatural paranormal haunting disappearance fear ghost

In [624]:
def clean_data(x):
    if isinstance(x,list):
        return [str.lower(i.replace(" ",'')) for i in x ]
    else:
        if isinstance(x,str):
            return str.lower(x.replace(' ',''))
        else:
            return ''

In [625]:
cols=old_data.columns
for col in cols:
    if col!='movie_title':
        old_data[col]=old_data[col].str.lower()

In [626]:
cols=['director_name','actor_1_name','actor_2_name','actor_3_name']
for col in cols:
    old_data[col]=old_data[col].apply(clean_data)

In [627]:
old_data.head()

,movie_title,genres,actor_1_name,actor_2_name,actor_3_name,director_name,keywords
0,Avatar,action adventure fantasy sci-fi,cchpounder,joeldavidmoore,wesstudi,jamescameron,avatar future marine native paraplegic
1,Pirates of the Caribbean: At World's End,action adventure fantasy,johnnydepp,orlandobloom,jackdavenport,goreverbinski,goddess marriage ceremony marriage proposal pirate singapore
2,Spectre,action adventure thriller,christophwaltz,rorykinnear,stephaniesigman,sammendes,bomb espionage sequel spy terrorist
3,The Dark Knight Rises,action thriller,tomhardy,christianbale,josephgordon-levitt,christophernolan,deception imprisonment lawlessness police officer terrorist plot
4,Star Wars: Episode VII - The Force Awakens,documentary,dougwalker,robwalker,unknown,dougwalker,unknown

In [629]:
old_data['soup']=old_data['genres']+' '+old_data['actor_1_name']+' '+old_data['actor_2_name']+' '+old_data['actor_3_name']+' '+old_data['director_name']+' '+old_data['keywords']

In [637]:
old_data['soup'][5529]

'drama romance crime danielkaluuya jodieturner-smith bokeemwoodbine melinamatsoukas on the run police officer killed black activist racist cop first date woman director killer on the run'

In [639]:
old_data.drop_duplicates(subset='movie_title',keep='last',inplace=True,ignore_index=True)

In [642]:
moviesid=pd.Series(old_data.index,index=old_data['movie_title'])
moviesid.head()

movie_title
Avatar                                                    0
Pirates of the Caribbean: At World's End                  1
Spectre                                                   2
The Dark Knight Rises                                     3
Star Wars: Episode VII - The Force Awakens                4
dtype: int64

In [643]:
old_data.isnull().sum()

movie_title      0
genres           0
actor_1_name     0
actor_2_name     0
actor_3_name     0
director_name    0
keywords         0
soup             0
dtype: int64

In [682]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn import metrics
vect=TfidfVectorizer(stop_words='english',analyzer='word',ngram_range=(1,1),use_idf=True)
matrix=vect.fit_transform(old_data['soup'])

In [683]:
cosine_sim=metrics.pairwise.linear_kernel(matrix,matrix)

In [684]:
def recommend(movie,number,sim=cosine_sim):
    idx=moviesid[movie]
    li=list(enumerate(sim[idx]))
    li=sorted(li,key = lambda x:x[1] , reverse=True)
    li=li[1:number+1]
    res=[x[0] for x in li]
    return old_data['movie_title'].iloc[res]

In [685]:
recommend('Inception',15)

3                   The Dark Knight Rises
2888                               Cypher
1538                               Looper
3540                              Don Jon
284                       Treasure Planet
67            G.I. Joe: The Rise of Cobra
2030                   Out of the Furnace
3690                         Take Shelter
613                          Total Recall
1070                  Miracle at St. Anna
1403                         Premium Rush
1281    3rd Rock from the Sun
1084                            The Juror
114                    Mad Max: Fury Road
4112                           It Follows
Name: movie_title, dtype: object

In [686]:
recommend('The Avengers',15)

7                   Avengers: Age of Ultron
5236                      Avengers: Endgame
968                    Defiance
58                      Monsters vs. Aliens
2772                       Attack the Block
4612                                   Home
69                               Iron Man 2
4615                               Monsters
23               Captain America: Civil War
5082                           The Predator
74      Captain America: The Winter Soldier
605                     Saving Private Ryan
558                      Battle Los Angeles
799                           The Equalizer
669                          Chicken Little
Name: movie_title, dtype: object

In [679]:
vect2=CountVectorizer(stop_words='english',ngram_range=(1,2),analyzer='word')
mat=vect2.fit_transform(old_data['soup'])

In [680]:
cosine_sim2=metrics.pairwise.cosine_similarity(mat,mat)

In [681]:
recommend('Avengers: Endgame',15,cosine_sim2)

4989          Avengers: Infinity War
439                 The Time Machine
746                     The Avengers
5130    The Girl in the Spider's Web
1250                   Just Visiting
5263                    Dark Phoenix
2854                      About Time
3562               Somewhere in Time
3138                 Poltergeist III
2264              Back to the Future
5301                Light of My Life
5036            Ant-Man and the Wasp
5082                    The Predator
84                      Interstellar
5403                    Little Women
Name: movie_title, dtype: object